%% PART 2: PATH PLANNING

%% Test your path planning algorithm 
% by generating the path between at least 10 randomly generated
% start/goal points in 2D in the House map and report the results.

n = 10; % n amount of maps we want to produce
np = 120; % npoints 

plan = prbroadmap(n, 120);

%% Making the robot follow the way-points
% generated by prbroadmap
n = 1;
np = 120;

figure(1)
plan = prbroadmap(n, np);

figure(2)
path = prmpath(plan, 10);
walking(path)